Support for LabJack DAQ devices
BCDA-APS/apstools pull request #890
Opened 2023-11-21 23:06 UTC by canismarko

Fixes  #879.

One note: I created a LabJackBase class and then subclass this for the various T-series devices (e.g. LabJackT4). Makes the code easy to maintain, but docstring don't seem to be inheriting properly on the sphinx autoapi.

2024-01-01 21:24 UTC, prjemian commented on apstools/devices/labjack.py
> +    pass
```suggestion
    """A generic output record."""
```

2024-01-01 21:24 UTC, prjemian commented on apstools/devices/labjack.py
> +various inputs/outputs available on the LabJack T-series. These means
```suggestion
various inputs/outputs available on the LabJack T-series.
```

2024-01-01 21:24 UTC, prjemian commented on apstools/devices/labjack.py
> +that individual inputs can be used as part of other devices. Assuming
```suggestion
Individual inputs can be used as part of other devices. Assuming
```

2024-01-01 21:26 UTC, prjemian commented on apstools/devices/labjack.py
> +These devices are **based on the v3.0.0 EPICS module**. The EPICS IOC
```suggestion
These devices are **based on EPICS LabJack module R3.0**. The EPICS IOC
```

2024-01-01 21:26 UTC, prjemian commented on apstools/devices/labjack.py
> +database changed significantly from v2 to v3 when the module was
```suggestion
database changed significantly from R2 to R3 when the module was
```

2024-01-01 21:27 UTC, prjemian commented on apstools/devices/labjack.py
> +rewritten to use the LJM library.
```suggestion
rewritten to use the LJM library.

.. see:: https://github.com/epics-modules/LabJack/releases/tag/R3-0
```

2024-01-01 21:27 UTC, prjemian commented on apstools/devices/labjack.py
> +    pass
this line can be removed

2024-01-01 21:30 UTC, prjemian commented on apstools/devices/labjack.py
> +def make_analog_outputs(num_ais: int):
```suggestion
def make_analog_outputs(num_aos: int):
```

2024-01-01 21:31 UTC, prjemian commented on apstools/devices/labjack.py
> +    for n in range(num_ais):
```suggestion
    for n in range(num_aos):
```

2024-01-01 21:33 UTC, prjemian commented on apstools/devices/labjack.py
> +    \\* The number of inputs and digital outputs depends on the specific
```suggestion
    The number of inputs and digital outputs depends on the specific
```

2024-01-01 21:37 UTC, prjemian requested changes
LGTM, minor documentation changes.  Happy New Year!

2024-01-02 04:21 UTC, canismarko reviewed
Thanks for the feedback. Changes made as suggested and added as several new commits.

2024-01-02 05:28 UTC, prjemian approved these changes
Great! Thanks for the contribution!

2024-01-02 11:31 UTC, merged